[laskar2004]
git-tree-sha1 = "e4044f4093e731021a3e62428f594ee7b5ea56e2"

    [[laskar2004.download]]
    sha256 = "8b3a9510ade307e1834c51968421ab803d0d570f1c27529cb417d7a185fbcc3e"
    url = "https://data.caltech.edu/records/v9dp1-jb227/files/laskar2004.tar.gz"

[cmip_monthly_tsi]
git-tree-sha1 = "a994acbf9906fbf605393420c153f7918fbbb66f"

    [[cmip_monthly_tsi.download]]
    sha256 = "7c7c8583a79dd5c28da494646674dc8911d66c9a983830df8b37d90b28f89fdd"
    url = "https://caltech.box.com/shared/static/nkz3rb8sm5y91p5tlagoe8bdbvdcj5iq.gz"
