[laskar2004]
git-tree-sha1 = "e4044f4093e731021a3e62428f594ee7b5ea56e2"

    [[laskar2004.download]]
    sha256 = "8b3a9510ade307e1834c51968421ab803d0d570f1c27529cb417d7a185fbcc3e"
    url = "https://data.caltech.edu/records/v9dp1-jb227/files/laskar2004.tar.gz"

[cmip_monthly_tsi]
git-tree-sha1 = "2b90616648c16638f21e06e386d61b11c3ed5f71"

    [[cmip_monthly_tsi.download]]
    sha256 = "821a88ed307a7c23988dd8e322d3405f6bdd5acd689c4e80decbc9c73022c661"
    url = "https://caltech.box.com/shared/static/nkz3rb8sm5y91p5tlagoe8bdbvdcj5iq.gz"
